import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import Button from "@/components/button";
import {
  accept,
  brands,
  successStory,
  speciality,
  joinNFT,
  Testimonials,
} from "@/data/fakeData";

import Nav from "@/components/nav";

import Logo from "@/public/svg/Logo.svg";
import Dot from "@/public/svg/Dot.svg";
import TestimonialsSvg from "@/public/svg/Testimonial.svg";
import Address from "@/public/svg/Address.svg";
import Phone from "@/public/svg/Phone.svg";
import Mail from "@/public/svg/Mail.svg";
import fb from "@/public/svg/socialNetwork/fb.svg";
import tw from "@/public/svg/socialNetwork/tw.svg";
import inSvg from "@/public/svg/socialNetwork/in.svg";
import yt from "@/public/svg/socialNetwork/yt.svg";

import BANNER_1 from "@/public/svg/banner/banner1.svg";
import BANNER_2 from "@/public/svg/banner/banner2.svg";
import BANNER_3 from "@/public/svg/banner/banner3.svg";
import BANNER_4 from "@/public/svg/banner/banner4.svg";
import BANNER_5 from "@/public/svg/banner/banner5.svg";
import BANNER_6 from "@/public/svg/banner/banner6.svg";
import BANNER_7 from "@/public/svg/banner/banner7.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>ThreeB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Nav />

        <div className={styles.boxContent1}>
          <div className={styles.left}>
            <h1>World Class Automated Crypto Trading Bot </h1>
            <p>
              Become a better trader. Powerful, AI-powered crypto trading bot to
              help you save time, trade 24/7, and automate your trading.
            </p>
            <Button className={styles.boxBtn}>Get Connected</Button>
          </div>
          <div className={styles.right}>
            <Image src={BANNER_1} alt="" />
          </div>
        </div>

        <div className={styles.boxContent2}>
          <p>We are ThreeB</p>
          <div>
            <p>We accept:</p>
            {accept?.map?.((item) => (
              <Image
                key={item.id}
                src={item.img}
                alt=""
                width={36}
                height={36}
              />
            ))}
          </div>
        </div>

        <div className={styles.boxContent3}>
          <hr />
          <div>Trusted by 500,000 traders from</div>
        </div>
        <div className={styles.boxContent4}>
          {brands?.map?.((item) => (
            <Image
              key={item.id}
              src={item.img}
              alt=""
              width={160}
              height={70}
            />
          ))}
          <div>15+ more</div>
        </div>

        <div className={styles.boxContent5}>
          <div>
            <div>
              <Image src={BANNER_2} alt="" width={462} height={414} />
            </div>

            <div className={styles.boxItem}>
              {successStory?.map?.((item) => (
                <div key={item?.id} className={styles.info}>
                  <div className={styles.infoContent}>
                    <Image src={item?.img} alt="" width={66} height={66} />
                    <div>{item?.content}</div>
                    <p>{item?.subContent}</p>
                  </div>
                  <div className={styles.rule}></div>
                </div>
              ))}
              <Image
                src={BANNER_2}
                alt=""
                width={462}
                height={414}
                className={styles.mobileBanner}
              />
            </div>
          </div>
        </div>
        <div className={styles.boxContent6}>
          <div className={styles.left}>
            <div className={styles.boxY}>
              <span>About Us</span>
            </div>
            <h1>The Future of Crypto Trading</h1>
            <p>
              Add automation to your CeFi and DeFi trading, and join the most
              popular social trading platform in the crypto industry.
            </p>
            <p>
              Thousands of cryptocurrency hobbyists, professionals, and
              institutional investors rely on HaasOnline as their preferred
              platform for automating crypto trading strategies.
            </p>
            <Button className={styles.boxBtn}>More About Us</Button>
          </div>
          <div className={styles.right}>
            <Image src={BANNER_3} alt="" width={541} height={339} />
          </div>
        </div>

        <div className={styles.boxContent7}>
          <div className={styles.boxY}>
            <span>Easy . Effective . World class</span>
          </div>
          <h1>Go down the rabbit hole</h1>
          <p>
            Take advantage of crypto trading with our automated trading toolset.
          </p>
          <div className={styles.boxSpeciality}>
            {speciality?.map?.((item) => (
              <div key={item?.id}>
                <div>
                  <Image src={item.img} alt="" width={105} height={105} />
                </div>
                <div className={styles.title}>{item?.title}</div>
                <p>{item?.content}</p>
              </div>
            ))}
          </div>
        </div>

        <div className={styles.boxContent8}>
          <div className={styles.boxY}>
            <span>Join Our Platform</span>
          </div>
          <h1>Powerful All-in-One Platform for Cryptocurrency Trading</h1>
          <div className={styles.content}>
            <div className={styles.left}>
              {joinNFT?.map?.((item) => (
                <div className={styles.item} key={item?.id}>
                  <div>
                    <Image src={item?.img} alt="" width={40} height={40} />
                  </div>
                  <div className={styles.rule}></div>
                  <div className={styles.boxContent}>
                    <div className={styles.title}>{item.title}</div>
                    <p>{item?.content}</p>
                  </div>
                </div>
              ))}
            </div>
            <div className={styles.right}>
              <Image src={BANNER_4} alt="" width={539} height={616} />
            </div>
          </div>
        </div>

        <div className={styles.boxContent9}>
          <div className={styles.boxY}>
            <span>Token Information</span>
          </div>
          <div className={styles.boxContent}>
            <div className={styles.left}>
              <h1>ThreeB makes our world go round</h1>
              <p>
                Our Tokens with a realworld use case created on the blockchain
                network.
              </p>
              <Button className={styles.boxBtn}>Buy Token</Button>
            </div>
            <div className={styles.right}>
              <Image src={BANNER_5} alt="" width={540} height={350} />
            </div>
          </div>
        </div>

        <div className={styles.boxContent10}>
          <div className={styles.boxTitle}>
            <div className={styles.boxY}>
              <span>Road Map</span>
            </div>
            <h1>ThreeB Timeline</h1>
            <p>
              This roadmap outlines our goals and where we want to take people
              to the ThreeB universe.
            </p>
          </div>

          <div className={styles.boxContent}>
            <div className={styles.left}>
              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>Late 2022 - Early 2023</span>
                </div>
                <div className={styles.connect}>
                  <div></div>
                  <Image src={Dot} alt="" width={19} height={19} />
                </div>
                <h2>Preparation</h2>
                <div className={styles.rule}></div>
                <p>
                  Market Research, Ideas Verification, Team Forming, Graphic
                  Design, Partnerships Onboard, Fund Raising – Strategic
                  Investors.
                </p>
              </div>
              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>Q3 2023</span>
                </div>
                <div className={styles.connect}>
                  <div></div>
                  <Image src={Dot} alt="" width={19} height={19} />
                </div>
                <h2>Eco-system Official Launch</h2>
                <div className={styles.rule}></div>
                <p>
                  Eco-system - NFT Marketplace, CEX, DEX - Official Launch,
                  Token Lists On Tier-2 CEX, Token Buybacks Program, Reach 500k
                  Users.
                </p>
              </div>
              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>More</span>
                </div>
                <div className={styles.connect}>
                  <div></div>
                  <Image src={Dot} alt="" width={19} height={19} />
                </div>
                <h2>Go Global</h2>
                <div className={styles.rule}></div>
                <p>
                  Applied more AI Bots, created many modern algorithms, Token
                  Lists On Tier-1 CEX & DEX, Target to reach more than 1M Users.
                </p>
              </div>
            </div>

            <div className={styles.midd}>
              <Image src={Dot} alt="" width={11} height={11} />
              <div></div>
              <Image src={Dot} alt="" width={11} height={11} />
            </div>

            <div className={styles.right}>
              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>Q2 2023</span>
                </div>
                <div className={styles.connect}>
                  <Image src={Dot} alt="" width={19} height={19} />
                  <div></div>
                </div>
                <h2>Platform Official Launch</h2>
                <div className={styles.rule}></div>
                <p>
                  ThreeB Platform - STO, Prediction, Bot Trading - Official
                  Launch, Airdrop on Global Sites, Community Development, KOLs &
                  VCs Onboard.
                </p>
              </div>
              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>Q4 2023</span>
                </div>
                <div className={styles.connect}>
                  <Image src={Dot} alt="" width={19} height={19} />
                  <div></div>
                </div>
                <h2>Growth-hack Marketing</h2>
                <div className={styles.rule}></div>
                <p>
                  Target to reach 100k Users, Governance launch, Upgrade the
                  platform to version 2.0 for more intelligent.
                </p>
              </div>
            </div>
          </div>

          <Button className={styles.boxBtn}>View Full Road Map</Button>
        </div>

        <div className={styles.boxContent10MB}>
          <div className={styles.boxTitle}>
            <div className={styles.boxY}>
              <span>Road Map</span>
            </div>
            <h1>ThreeB Timeline</h1>
            <p>
              This roadmap outlines our goals and where we want to take people
              to the ThreeB universe.
            </p>
          </div>

          <div className={styles.boxContent}>
            <div className={styles.midd}>
              <Image src={Dot} alt="" width={11} height={11} />
              <div></div>
              <Image src={Dot} alt="" width={11} height={11} />
            </div>

            <div className={styles.right}>
              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>Late 2022 - Early 2023</span>
                </div>
                <div className={styles.connect}>
                  <Image src={Dot} alt="" width={19} height={19} />
                  <div></div>
                </div>
                <h2>Preparation</h2>
                <div className={styles.rule}></div>
                <p>
                  Market Research, Ideas Verification, Team Forming, Graphic
                  Design, Partnerships Onboard, Fund Raising – Strategic
                  Investors.
                </p>
              </div>

              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>Q2 2023</span>
                </div>
                <div className={styles.connect}>
                  <Image src={Dot} alt="" width={19} height={19} />
                  <div></div>
                </div>
                <h2>Platform Official Launch</h2>
                <div className={styles.rule}></div>
                <p>
                  ThreeB Platform - STO, Prediction, Bot Trading - Official
                  Launch, Airdrop on Global Sites, Community Development, KOLs &
                  VCs Onboard.
                </p>
              </div>

              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>Q3 2023</span>
                </div>
                <div className={styles.connect}>
                  <Image src={Dot} alt="" width={19} height={19} />
                  <div></div>
                </div>
                <h2>Eco-system Official Launch</h2>
                <div className={styles.rule}></div>
                <p>
                  Eco-system - NFT Marketplace, CEX, DEX - Official Launch,
                  Token Lists On Tier-2 CEX, Token Buybacks Program, Reach 500k
                  Users.
                </p>
              </div>
              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>Q4 2023</span>
                </div>
                <div className={styles.connect}>
                  <Image src={Dot} alt="" width={19} height={19} />
                  <div></div>
                </div>
                <h2>Growth-hack Marketing</h2>
                <div className={styles.rule}></div>
                <p>
                  Target to reach 100k Users, Governance launch, Upgrade the
                  platform to version 2.0 for more intelligent.
                </p>
              </div>
              <div className={styles.card}>
                <div className={styles.boxY}>
                  <span>More</span>
                </div>
                <div className={styles.connect}>
                  <Image src={Dot} alt="" width={19} height={19} />
                  <div></div>
                </div>
                <h2>Go Global</h2>
                <div className={styles.rule}></div>
                <p>
                  Applied more AI Bots, created many modern algorithms, Token
                  Lists On Tier-1 CEX & DEX, Target to reach more than 1M Users.
                </p>
              </div>
            </div>
          </div>

          <Button className={styles.boxBtn}>View Full Road Map</Button>
        </div>

        <div className={styles.boxContent11}>
          <div className={styles.midTitle}>
            <div className={styles.boxY}>
              <span>Testimonials</span>
            </div>
            <h1>What Our client say</h1>
            <p>
              Our clients send us bunch of smilies with our services and we love
              them
            </p>
          </div>

          <div className={styles.testimonials}>
            {Testimonials?.map?.((item) => (
              <div key={item?.id} className={styles.item}>
                <div className={styles.avatar}>
                  <Image src={item?.img} alt="" width={104} height={104} />
                </div>
                <div className={styles.name}>{item?.name}</div>
                <div className={styles.subName}>{item?.subtitle}</div>
                <Image src={TestimonialsSvg} width={30} height={30} />
                <p>{item?.content}</p>
              </div>
            ))}
          </div>
        </div>

        <div className={styles.boxContent12}>
          <div className={styles.midTitle}>
            <div className={styles.boxY}>
              <span>Get in Touch!</span>
            </div>
            <h1>Let’s Start Working Together</h1>
          </div>
          <div className={styles.boxContent}>
            <div className={styles.left}>
              <div>
                <div className={styles.title}>Contact information</div>
                <div className={styles.rule}></div>
                <div>
                  <div className={styles.boxInfo}>
                    <Image src={Address} alt="" width={16} height={16} />
                    <span>20, Backway Road, New York, US AB42</span>
                  </div>
                  <hr />
                  <div className={styles.boxInfo}>
                    <Image src={Phone} alt="" width={16} height={16} />
                    <span className={styles.strong}>+000-000-000-000</span>
                  </div>
                  <hr />
                  <div className={styles.boxInfo}>
                    <Image src={Mail} alt="" width={16} height={16} />
                    <span>support@gmail.com</span>
                  </div>
                </div>
              </div>
              <div>
                <Image src={BANNER_6} alt="" width={320} height={285} />
              </div>
            </div>
            <div className={styles.right}>
              <form action="#">
                <div>
                  <label for="name">Your name</label>
                  <br />
                  <input type="text" id="name" name="name" value="Jane" />
                </div>
                <div>
                  <label for="mail">Your email</label>
                  <br />
                  <input type="text" id="mail" name="mail" />
                </div>
                <div>
                  <label for="phone">Your phone</label>
                  <br />
                  <input type="text" id="phone" name="phone" />
                </div>
                <div>
                  <label for="subject">Subject</label>
                  <br />
                  <select name="subject" id="subject">
                    <option value="1">Option 1</option>
                    <option value="2">Option 2</option>
                  </select>
                </div>
                <div className={styles.difirent}>
                  <label for="message">Message</label>
                  <br />
                  <textarea
                    name="message"
                    id="message"
                    cols="30"
                    rows="10"
                  ></textarea>
                </div>
                <div className={styles.difirent}>
                  <Button className={styles.boxBtn}>Send Now</Button>
                </div>
              </form>
            </div>
          </div>
        </div>

        <div className={styles.boxContent13}>
          <div className={styles.boxContent}>
            <div className={styles.left}>
              <h1>Powering the Best Trading Community</h1>
              <p>
                The $ThreeB token allows ThreeB community to access trading
                tools at a low cost and participate in the social trading aspect
                of the platform.
              </p>
              <Button className={styles.boxBtn}>Join Now</Button>
            </div>
            <div className={styles.right}>
              <Image src={BANNER_7} alt="" width={539} height={379} />
            </div>
          </div>
        </div>

        <footer className={styles.footer}>
          <div>
            <div className={styles.boxLogo}>
              <Image src={Logo} alt="" width={160} height={38} />
            </div>
            <div className={styles.option}>
              <ul>
                <li>Home</li>
                <li>Explore</li>
                <li>About Us</li>
                <li>Tokenomics</li>
                <li>Roadmap</li>
                <li>Contact</li>
              </ul>
            </div>
            <div className={styles.media}>
              <Image src={fb} alt="" width={38} height={38} />
              <Image src={tw} alt="" width={38} height={38} />
              <Image src={inSvg} alt="" width={38} height={38} />
              <Image src={yt} alt="" width={38} height={38} />
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
